source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Demo_Example', :exclusive => true do
  pod "Demo", :path => "../"
end

target 'Demo_Tests', :exclusive => true do
  pod "Demo", :path => "../"

  pod 'FBSnapshotTestCase'
end
